### PR TITLE
feature/font-highlight-color

### PR DESCRIPTION
**Pull request by DKWoods**
In renaming my branch, I've achieved the "squashing" of all commits into a single document, but have lost our commentary trail.  I'll leave the previous branch in place for now if you want to review the older comments, and will close that pull request later.

### CODE REVIEW

**Comment by DKWoods** [comment]
I put the "print" in because without it, I get just the index number, while with it, I get the more descriptive text from the enumeration.

>>> f.highlight
5
>>>print f.highlight
PINK (5)

I wanted the example to match actual program behavior.

**Comment by scanny** [comment]
Ok David, this looks really good. Just a couple tweaks at the top and we're good to go.

I'll get a branch going on the main repo we can start merging these commits into and let you know the details once I have it done.

Next we can move along to the acceptance tests.

Have you had a chance to look at any of those and have any ideas? I'm inclined to think the ones for this will be almost exactly like some others that are there; so they should be cut-and-pasteable for the most part.

I'm thinking we can just add a couple Scenario Outlines to this existing test:
https://github.com/python-openxml/python-docx/blob/master/features/txt-font-props.feature

So it would go something like:

  @wip
  Scenario Outline: Get font highlight color
    Given a font having <color> highlighting
     Then font.highlight_color is <value>

    Examples: highlight_color values
      | color        | value        |
      | inherited    | None         |
      | default      | AUTO         |
      | yellow       | YELLOW       |
      | bright green | BRIGHT_GREEN |

and then another for setting font highlight color. Might as well insert them at the top so we don't have to scroll down to see them; order is basically arbitrary.

Note the `@wip` decorator. This causes this acceptance test to be skipped by the integration testing procedure. It's expected to fail until you get the implementation done. The @wip comes off once those are done.

Best,
Steve

On Feb 3, 2016, at 2:47 PM, David Woods <notifications@github.com<mailto:notifications@github.com>> wrote:


In renaming my branch, I've achieved the "squashing" of all commits into a single document, but have lost our commentary trail. I'll leave the previous branch in place for now if you want to review the older comments, and will close that pull request later.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/python-openxml/python-docx/pull/257

Commit Summary

  *   Update font-color-highlight analysis document

File Changes

  *   A docs/dev/analysis/features/text/font-highlight-color.rst<https://github.com/python-openxml/python-docx/pull/257/files#diff-0> (187)

Patch Links:

  *   https://github.com/python-openxml/python-docx/pull/257.patch
  *   https://github.com/python-openxml/python-docx/pull/257.diff

**Comment by scanny** [comment]
Ok, I'm cool with that :)

Best,
Steve

On Feb 3, 2016, at 3:12 PM, David Woods <notifications@github.com<mailto:notifications@github.com>> wrote:


I put the "print" in because without it, I get just the index number, while with it, I get the more descriptive text from the enumeration.

f.highlight
5
print f.highlight
PINK (5)

I wanted the example to match actual program behavior.

**Comment by scanny** [comment]
good idea, thanks for letting me know David :)

Best,
Steve

On Feb 3, 2016, at 2:47 PM, David Woods <notifications@github.com<mailto:notifications@github.com>> wrote:


In renaming my branch, I've achieved the "squashing" of all commits into a single document, but have lost our commentary trail. I'll leave the previous branch in place for now if you want to review the older comments, and will close that pull request later.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/python-openxml/python-docx/pull/257

Commit Summary

  *   Update font-color-highlight analysis document

File Changes

  *   A docs/dev/analysis/features/text/font-highlight-color.rst<https://github.com/python-openxml/python-docx/pull/257/files#diff-0> (187)

Patch Links:

  *   https://github.com/python-openxml/python-docx/pull/257.patch
  *   https://github.com/python-openxml/python-docx/pull/257.diff

**Comment by DKWoods** [comment]
For acceptance testing, please take a look at:
https://github.com/DKWoods/python-docx/commit/b0203848b42d2133140e467af6b1c7ebd869971b

This modified tests/text/test_font.py to add tests for getting and setting font highlight.  I haven't changed it to reflect the change from WD_COLORINDEX to WD_COLOR_INDEX yet, not the change of the property to highlight_color, but should give you a good idea where I think I need to head.  

It tests getting and setting all allowed highlight colors, as well as changing and removing highlight colors.  I should be able to make the WD_COLOR_INDEX change and the highlight_color change tomorrow morning.

**Comment by scanny** [comment]
Hi David -- these are unit tests, rather than acceptance tests. python-docx has a two-level test strategy, basically unit and integration levels. The acceptance tests are an integration test, exercising the capability from the API all the way down and back and using actual Word files instead of the stubs and so forth that make sense at the unit (isolated) level.

In general, the acceptance tests *drive* the unit tests; in the sense that the unit test to be developed is determined by where the acceptance test currently errors out. So the acceptance tests come very early, right after analysis and before implementation.

That said, these look good. I can take a closer look when we get to that stage. In the final commit sequence these would show up in separate commits, each with the code that makes that test pass.

Let me know if you need more :)

**Comment by scanny** [comment]
Btw, it just occurred to me. The acceptance test(s) basically exercise the protocol in the analysis document. So once the protocol is resolved, the acceptance test is to a large degree just implementing that in Cucumber (the acceptance testing language) to verify the API works as designed, end-to-end. Then the unit tests exercise the bits and pieces in isolated chunks. You really need both to establish reasonable assurance things are working the way you intended, and still working after future changes.

This last bit is an important motivator for having tests, even if you know exactly how to build a working implementation without them. They constitute your assurance that no one else will break your code going forward because no commits will be merged if they don't pass all the tests, including yours :)

**Comment by DKWoods** [comment]
I've now added the Acceptance Tests

**Comment by DKWoods** [comment]
I've now checked in code changes for the implementation of feature/highlight, including unit tests.  There seems to be a bit of weirdness with docx/enum/text.py.  My copy doesn't show your recent changes, despite synching the repositories, but I don't think I did anything that would affect that on your end.

**Comment by scanny** [comment]
Nothing you do on your side can affect the main repo because you don't have write privileges to that one, so no worries there :)

But you would have had to separately started tracking the feature/highlight branch on the main repo. I believe it would show up on your side as 'python-openxml/feature/highlight'.

This command would show it as such if it were there:
```bash
$ git branch -r  # list remote branches
```

If it doesn't appear, this will get it:
```bash
$ git fetch <remote> feature/highlight
```

This would require you have the python-oxml repo defined as a remote, then you substitute that name (probably 'python-openxml') for <remote>. This git command lists your defined remotes:
```bash
$ git remote
```

I expect 'origin' on your machine points to the DKWoods repo. If your repo is a direct clone of the python-oxml version then 'origin' would point to the main repo and you'd have a 'DKWoods' remote.

Let me know if you need more :)

**Comment by scanny** [comment]
Feature completed and merged into develop. Font.highlight_color will be included in the next release.

**Pull request closed without merging**
