### PR TITLE
Include hyperlink text in paragraph.text

### PR DESCRIPTION
**Pull request by br-rkdrnf**
Included hyperlink text in `paragraph.text`, added new property `inline_items` in `paragraph` to iterate both `run` and `hyperlink` in paragraph.

### CODE REVIEW

**Comment by pzbitskiy** [comment]
I like the change, thank you for implementing this. Couple thoughts although:
1. Test is needed.
2. I understand a current design, it reflects `w:p`, `w:r`, `w:hyperlink` in xml. In my opinion having both `runs` and `inline_items` makes things more complicated. How about letting `runs` to return both `Run` and `HyperLink` instances and inheriting `HyperLink` from `Run` (since it is `w:r`with additional `r:id` prop). Inheritance is a good choice here because of enforcing `Run` interface.
On the client side a user can check for `Run`/`HyperLink` type and access additional props in `HyperLink`.

@scanny Could you please take a look at this PR?

**Comment by linuxkd** [comment]
Bump @scanny - This would be a very welcome addition.

**Comment by pzbitskiy** [comment]
@br-rkdrnf feel free to grab a test from here: https://github.com/pzbitskiy/python-docx/commit/a3308f33aa2358a8aab274fbd341578d9ded9c82#diff-009212de519b6c351067499fdea10863R1

**Comment by svobora** [comment]
They killed @scanny bastards!

**Comment by alankashkash** [comment]
Hey. Why wasn't it published? I'm quite new to PRs on Github. Do you guys know if I can merge this PR to my local fork of this library? This feature might really come in handy

**Pull request closed without merging**
