### PR TITLE
Supports python 3.3 -> 3.8 

### PR DESCRIPTION
**Pull request by jochman**
added py3.7 and up to setup.py
updated very outdated requirements

### CODE REVIEW

**Comment by lifuzu** [comment]
+1

**Review by creyD — APPROVED** [review]
Looks simple enough. Are there problems with Python 3.10 though?

**Review by jochman — COMMENTED** [review]
add py10

**Comment by jochman** [comment]
lets see

**Comment by jochman** [comment]
Well, tox passed 😊

**Comment by jochman** [comment]
@creyD I hope you'll get the message soon. The last time I committed, there were two python versions ago.

**Comment by creyD** [comment]
Oh sorry, I am not a maintainer of this repo, I don't have the right to merge this or anything similar.

**Comment by jochman** [comment]
project updated since then with different things.

**Pull request closed without merging**
