### PR TITLE
Add basic support for adding SVG pictures to docx files

### PR DESCRIPTION
**Pull request by takis**
See issues #351, #651, #659.

### CODE REVIEW

**Comment by liam-veitch** [comment]
Hi @takis thanks for the improvement - for my SVG files produced by matplotlib there are relative scalings in the width and height attributes. I had to take the data from the viewbox attribute:

Scaling is not great in document, but maybe you know the cause?

Example svg header:
`<svg baseProfile='full' height='100.000000%' version='1.1' viewBox='0.000000 0.000000 1240.000000 1753.000000' width='100.000000%' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink'>`

in svg.py:
```
    @classmethod
    def _dimensions_from_stream(cls, stream):
        stream.seek(0)
        data = stream.read()
        root = ET.fromstring(data)
        # FIXME: The width could be expressed as '4cm'
        # See https://www.w3.org/TR/SVG11/struct.html#NewDocument
        width_str = root.attrib["width"]
        height_str = root.attrib["height"]
        if r'%' in width_str and r'%' in height_str:
            vb_lims = str(root.attrib["viewBox"]).split(' ')
            width_scale = float(width_str.strip(r'%')) * 0.01
            height_scale = float(height_str.strip(r'%')) * 0.01
            width = int(width_scale * float(vb_lims[2]))
            height = int(height_scale * float(vb_lims[3]))
        else:
            width = int(root.attrib["width"])
            height = int(root.attrib["height"])

        return width, height
```

**Comment by JaverHumberto** [comment]
Hi @takis, I'm new using docx (and python), and I'm tryng to load some SVG images in a word document, looking for that I found this, but try to replicate the code you were testing with and it doesn't work for me, I get the docx.image.exceptions.UnrecognizedImageError. So it isn't "included" in docx now? if not, is there a way for using your code? thanks in advance, and sorry if it's not a place for asking this, i'll remove the comment if needed.

**Comment by Kladdy** [comment]
This would be amazing if it could be merged into a new release. In the meantime, if somebody wants to play around with SVG files, I created a monkey patch just as was made in the case for EMF files: https://github.com/python-openxml/python-docx/pull/196#issuecomment-758974499. Just add the code from the gist below to a file called `docx_svg_patch.py`, and at the top of your own python script you have `import docx_svg_patch`. I haven't tested this extensively, and I am not sure how well this plays with other image types now, but it's at least a start.

Link to gist: https://gist.github.com/Kladdy/d3bdb9bbf2c38d4f194ea9a7904fc3f2

**Comment by takis** [comment]
> Hi @takis, I'm new using docx (and python), and I'm tryng to load some SVG images in a word document, looking for that I found this, but try to replicate the code you were testing with and it doesn't work for me, I get the docx.image.exceptions.UnrecognizedImageError. So it isn't "included" in docx now? if not, is there a way for using your code? thanks in advance, and sorry if it's not a place for asking this, i'll remove the comment if needed.

Hi @JaverHumberto, no, unfortunately, the code was not merged. I've created a new pull request and updated the code though. If you want to try it, you can use my fork for now:
https://github.com/takis/python-docx/

**Comment by takis** [comment]
Hi @Kladdy 

I've updated the pull request and I'm also still hoping that it will get merged one day.

**Comment by takis** [comment]
Hi @goomesthiago 

Unfortunately not, but I do try to keep my fork in sync with the main repository.

**Pull request closed without merging**
