### PR TITLE
comments

### PR DESCRIPTION
**Pull request by aboater**
The comments part is added.

### CODE REVIEW

**Comment by zyzstat** [comment]
Hi Aboater

Does this mean we can use comments part in python-docx now?

BR,

zyzstat

**Comment by aboater** [comment]
Hello @zyzstat ，
You can use comments part in python-docx now. My code isn't goot enough, but it can be used.

**Comment by zyzstat** [comment]
> Hello @zyzstat ，
> You can use comments part in python-docx now. My code isn't goot enough, but it can be used.

Thank you!

**Comment by aboater** [comment]
> > Hello @zyzstat ，
> > You can use comments part in python-docx now. My code isn't goot enough, but it can be used.
> 
> Thank you!

You are welcome. I also need it.

**Comment by aboater** [comment]
> > Hello @zyzstat ，
> > You can use comments part in python-docx now. My code isn't goot enough, but it can be used.
> 
> Thank you!

You are welcome. I also need it.

**Comment by zyzstat** [comment]
> > > Hello @zyzstat ，
> > > You can use comments part in python-docx now. My code isn't goot enough, but it can be used.
> > 
> > 
> > Thank you!
> 
> You are welcome. I also need it.

Well. I installed your package from github. But it still can not import a docx.Comments in python.
Can you give me some hints? 
Thanks a lot!

**Comment by aboater** [comment]
Show me your error of the code. If I can solve it, I will help you.------------------ 原始邮件 ------------------
发件人: "zyzstat"<notifications@github.com>
发送时间: 2019年11月12日(星期二) 晚上9:46
收件人: "python-openxml/python-docx"<python-docx@noreply.github.com>;
抄送: "aboater"<2374440151@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [python-openxml/python-docx] comments (#705)


   
Hello @zyzstat ，
 You can use comments part in python-docx now. My code isn't goot enough, but it can be used.
  
Thank you!
  
You are welcome. I also need it.
  
Well. I installed your package from github. But it still can not import a docx.Comments in python.
 Can you give me some hints?
 Thanks a lot!
 
&mdash;

**Comment by zyzstat** [comment]
> Show me your error of the code. If I can solve it, I will help you.------------------ 原始邮件 ------------------ 发件人: "zyzstat"<notifications@github.com> 发送时间: 2019年11月12日(星期二) 晚上9:46 收件人: "python-openxml/python-docx"<python-docx@noreply.github.com>; 抄送: "aboater"<2374440151@qq.com>;"State change"<state_change@noreply.github.com>; 主题: Re: [python-openxml/python-docx] comments (#705) Hello @zyzstat ， You can use comments part in python-docx now. My code isn't goot enough, but it can be used. Thank you! You are welcome. I also need it. Well. I installed your package from github. But it still can not import a docx.Comments in python. Can you give me some hints? Thanks a lot! &mdash; You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

It's a stupid question that i don't know how to use your comment part.😂
Such as document.add_paragraph(), i don't know if there is a docx.comments() function in docx.
Can you show me a example that how to insert comment in a document?

**Comment by aboater** [comment]
OK，I will look for a&nbsp;example for you tomorrow.&nbsp; By the way, please use Chinese if you can.

---Original---

**Comment by zyzstat** [comment]
> OK，I will look for a&nbsp;example for you tomorrow.&nbsp; By the way, please use Chinese if you can.
> […](#)
> ---Original--- From: "zyzstat"<notifications@github.com&gt; Date: Tue, Nov 12, 2019 22:25 PM To: "python-openxml/python-docx"<python-docx@noreply.github.com&gt;; Cc: "State change"<state_change@noreply.github.com&gt;;"aboater"<2374440151@qq.com&gt;; Subject: Re: [python-openxml/python-docx] comments (#705) Show me your error of the code. If I can solve it, I will help you.------------------ 原始邮件 ------------------ 发件人: "zyzstat"notifications@github.com 发送时间: 2019年11月12日(星期二) 晚上9:46 收件人: "python-openxml/python-docx"python-docx@noreply.github.com; 抄送: "aboater"2374440151@qq.com;"State change"state_change@noreply.github.com; 主题: Re: [python-openxml/python-docx] comments (#705) Hello @zyzstat ， You can use comments part in python-docx now. My code isn't goot enough, but it can be used. Thank you! You are welcome. I also need it. Well. I installed your package from github. But it still can not import a docx.Comments in python. Can you give me some hints? Thanks a lot! — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. It's a stupid question that i don't know how to use your comment part.😂 Such as document.add_paragraph(), i don't know if there is a docx.comments() function in docx. Can you show me a example that how to insert comment in a document? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

哈哈哈好的，太感谢了，早点休息

**Comment by aboater** [comment]
我靠，老哥英语好啊



---Original---

**Comment by zyzstat** [comment]
我还a example呢，英语垃圾，那等你不忙教教我插入comment吧

Best,

Yingzhou

**Comment by aboater** [comment]
好说好说，今天关电脑了，明天给你找。



---Original---

**Comment by zyzstat** [comment]
好👌，也可以加个wx 15115428008
太感谢了
Best,

Yingzhou

**Comment by aboater** [comment]
好的，暗号：批注



---Original---

**Comment by aboater** [comment]
一个简单的demo，请查收


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zyzstat"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 晚上10:54
收件人:&nbsp;"python-openxml/python-docx"<python-docx@noreply.github.com&gt;;
抄送:&nbsp;"欧享虎"<2374440151@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [python-openxml/python-docx] comments (#705)



好👌，也可以加个wx 15115428008
 太感谢了
 Best,
 
 Yingzhou
 
 &gt; 在 2019年11月12日，22:51，aboater <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿好说好说，今天关电脑了，明天给你找。 
 &gt; 
 &gt; 
 &gt; 
 &gt; ---Original--- 
 &gt; From: "zyzstat"<notifications@github.com&amp;gt; 
 &gt; Date: Tue, Nov 12, 2019 22:47 PM 
 &gt; To: "python-openxml/python-docx"<python-docx@noreply.github.com&amp;gt;; 
 &gt; Cc: "State change"<state_change@noreply.github.com&amp;gt;;"aboater"<2374440151@qq.com&amp;gt;; 
 &gt; Subject: Re: [python-openxml/python-docx] comments (#705) 
 &gt; 
 &gt; 
 &gt; 我还a example呢，英语垃圾，那等你不忙教教我插入comment吧 
 &gt; 
 &gt; Best, 
 &gt; 
 &gt; Yingzhou 
 &gt; 
 &gt; &amp;gt; 在 2019年11月12日，22:45，aboater <notifications@github.com&amp;gt; 写道： 
 &gt; &amp;gt; 
 &gt; &amp;gt; ﻿我靠，老哥英语好啊 
 &gt; &amp;gt; 
 &gt; &amp;gt; 
 &gt; &amp;gt; 
 &gt; &amp;gt; ---Original--- 
 &gt; &amp;gt; From: "zyzstat"<notifications@github.com&amp;amp;gt; 
 &gt; &amp;gt; Date: Tue, Nov 12, 2019 22:42 PM 
 &gt; &amp;gt; To: "python-openxml/python-docx"<python-docx@noreply.github.com&amp;amp;gt;; 
 &gt; &amp;gt; Cc: "State change"<state_change@noreply.github.com&amp;amp;gt;;"aboater"<2374440151@qq.com&amp;amp;gt;; 
 &gt; &amp;gt; Subject: Re: [python-openxml/python-docx] comments (#705) 
 &gt; &amp;gt; 
 &gt; &amp;gt; 
 &gt; &amp;gt; 
 &gt; &amp;gt; OK，I will look for a&amp;amp;nbsp;example for you tomorrow.&amp;amp;nbsp; By the way, please use Chinese if you can. 
 &gt; &amp;gt; … 
 &gt; &amp;gt; ---Original--- From: "zyzstat"<notifications@github.com&amp;amp;gt; Date: Tue, Nov 12, 2019 22:25 PM To: "python-openxml/python-docx"<python-docx@noreply.github.com&amp;amp;gt;; Cc: "State change"<state_change@noreply.github.com&amp;amp;gt;;"aboater"<2374440151@qq.com&amp;amp;gt;; Subject: Re: [python-openxml/python-docx] comments (#705) Show me your error of the code. If I can solve it, I will help you.------------------ 原始邮件 ------------------ 发件人: "zyzstat"notifications@github.com 发送时间: 2019年11月12日(星期二) 晚上9:46 收件人: "python-openxml/python-docx"python-docx@noreply.github.com; 抄送: "aboater"2374440151@qq.com;"State change"state_change@noreply.github.com; 主题: Re: [python-openxml/python-docx] comments (#705) Hello @zyzstat ， You can use comments part in python-docx now. My code isn't goot enough, but it can be used. Thank you! You are welcome. I also need it. Well. I installed your package from github. But it still can not import a docx.Comments in python. Can you give me some hints? Thanks a lot! — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. It's a stupid question that i don't know how to use your comment part.😂 Such as document.add_paragraph(), i don't know if there is a docx.comments() function in docx. Can you show me a example that how to insert comment in a document? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; &amp;gt; 
 &gt; &amp;gt; 哈哈哈好的，太感谢了，早点休息 
 &gt; &amp;gt; 
 &gt; &amp;gt; — 
 &gt; &amp;gt; You are receiving this because you modified the open/close state. 
 &gt; &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; &amp;gt; — 
 &gt; &amp;gt; You are receiving this because you were mentioned. 
 &gt; &amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
 &gt; 
 &gt; — 
 &gt; You are receiving this because you modified the open/close state. 
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.
 &gt; —
 &gt; You are receiving this because you were mentioned.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zyzstat** [comment]
老哥邮件没有附件，你发我邮箱吧zyzstat@foxmail.com
谢谢了

Best,

Yingzhou

**Comment by BatGrey** [comment]
你好，请问那个demo方便发我一份吗？
如果方便的话，这是我的邮箱
batgrey@stu.scau.edu.cn

**Comment by JoelWiebe** [comment]
It appears that this branch was deleted but never merged. 

Any chance this could be updated and merged into master? I noticed a number of people creating issues for "Comments" so there seems to be some interest in this.

**Pull request closed without merging**
